// Guía Profit First — contenido original basado en la metodología del libro,
// organizado por situación financiera. Estructura pensada para que a futuro
// un agente la lea junto con los datos reales del usuario y le aconseje.
// Cada consejo: { id, title, body, tags }  — tags = situaciones donde aplica.

export const ADVICE = [
  {
    id: "fundamentos",
    name: "Fundamentos del método",
    icon: "BookOpen",
    color: "teal",
    summary: "La base: por qué la ganancia va primero y cómo se aplica.",
    tips: [
      { id: "f1", title: "Invierte la fórmula", tags: ["negocio", "personal"],
        body: "En vez de Ventas − Gastos = Ganancia, usa Ventas − Ganancia = Gastos. Aparta primero tu ganancia y obliga a que los gastos se ajusten a lo que queda." },
      { id: "f2", title: "Separa el dinero por propósito", tags: ["negocio", "personal"],
        body: "Cada objetivo (ganancia, salario, impuestos, operación) vive en su propia cuenta. Si todo está junto, todo se gasta." },
      { id: "f3", title: "Reparte en fechas fijas", tags: ["negocio"],
        body: "En lugar de mover dinero cada vez que entra, hazlo dos veces al mes (por ejemplo el 10 y el 25). Te da ritmo y claridad de cuánto tienes de verdad." },
      { id: "f4", title: "Empieza pequeño", tags: ["negocio", "deudas"],
        body: "No arranques apartando 20% de ganancia. Empieza con 1%; casi no lo sientes, pero crea el hábito. Sube el porcentaje poco a poco cada trimestre." },
      { id: "f5", title: "Lo disponible se gasta", tags: ["negocio", "personal"],
        body: "Si el dinero está a la vista, encuentras en qué gastarlo. Al esconder la ganancia en otra cuenta, aprendes a operar con menos, sin darte cuenta." },
      { id: "f6", title: "Ajusta los porcentajes a tu tamaño", tags: ["negocio"],
        body: "Un negocio pequeño y uno grande no reparten igual. Revisa tus porcentajes objetivo conforme cambian tus ingresos, no los dejes fijos para siempre." },
    ],
  },
  {
    id: "deudas",
    name: "Salir de deudas",
    icon: "TrendingDown",
    color: "rose",
    summary: "Cómo dejar de acumular deuda y pagar la que ya tienes.",
    tips: [
      { id: "d1", title: "Aparta un porcentaje para deuda", tags: ["deudas"],
        body: "Crea una cuenta de 'Pago de deuda' y mándale un porcentaje fijo de cada ingreso, antes de gastar. Que abonar deje de depender de si 'sobró'." },
      { id: "d2", title: "Usa parte de la ganancia para abonar", tags: ["deudas", "negocio"],
        body: "Mientras tengas deuda, destina una porción de lo que apartas como ganancia a eliminarla. Es la ganancia trabajando para liberarte de intereses." },
      { id: "d3", title: "Ataca una deuda a la vez", tags: ["deudas"],
        body: "Concentra el abono extra en la deuda más pequeña (para ganar impulso) o en la de mayor interés (para ahorrar más). Elige una y no la sueltes hasta cerrarla." },
      { id: "d4", title: "No tapes gastos con más deuda", tags: ["deudas", "negocio"],
        body: "Si usas tarjeta o préstamos para cubrir la operación del mes, el hueco crece. La disciplina de repartir primero es justo lo que corta ese círculo." },
      { id: "d5", title: "Renegocia y ordena", tags: ["deudas"],
        body: "Llama a tus acreedores, busca menor tasa o consolidar. Bajar el interés hace que cada abono rinda más." },
    ],
  },
  {
    id: "rentabilidad",
    name: "Hacer rentable el negocio",
    icon: "Rocket",
    color: "amber",
    summary: "Que el negocio deje dinero de verdad, no solo movimiento.",
    tips: [
      { id: "r1", title: "Toma ganancia desde el día uno", tags: ["negocio"],
        body: "No esperes a 'estar grande' para ser rentable. Aparta ganancia desde ya, aunque sea mínima. La rentabilidad es un hábito, no un premio futuro." },
      { id: "r2", title: "Caza gastos fantasma", tags: ["negocio"],
        body: "Revisa suscripciones, servicios y proveedores cada trimestre. Cancela lo que no usas y negocia lo que sí. Cada dólar recortado es ganancia directa." },
      { id: "r3", title: "Sube márgenes antes que volumen", tags: ["negocio", "ingresos"],
        body: "Vender más barato y más veces puede dejarte igual o peor. Mejora precio o costo por unidad; un mejor margen hace todo más fácil." },
      { id: "r4", title: "Prioriza lo que genera caja", tags: ["negocio"],
        body: "Identifica qué productos o clientes dejan más ganancia real y ponles el foco. No todo lo que vende conviene." },
      { id: "r5", title: "Crecer sin rentabilidad es una trampa", tags: ["negocio"],
        body: "Facturar más mientras la ganancia sigue en cero solo agranda el problema. Primero asegura que cada venta deje algo." },
    ],
  },
  {
    id: "ingresos",
    name: "Generar más ingresos",
    icon: "TrendingUp",
    color: "lime",
    summary: "Formas de aumentar lo que entra, con lo que ya tienes.",
    tips: [
      { id: "i1", title: "Véndele más a quien ya te compra", tags: ["ingresos", "negocio"],
        body: "Es más barato venderle de nuevo a un cliente actual que conseguir uno nuevo. Ofrece complementos, mejoras o recompra." },
      { id: "i2", title: "Sube el ticket promedio", tags: ["ingresos", "negocio"],
        body: "Paquetes, versiones premium o combos suben lo que gasta cada cliente sin necesidad de más clientes." },
      { id: "i3", title: "Crea ingresos recurrentes", tags: ["ingresos", "negocio"],
        body: "Suscripciones, mantenimientos o planes mensuales dan una base estable de caja, más fácil de repartir con el método." },
      { id: "i4", title: "Activa referidos", tags: ["ingresos"],
        body: "Un cliente contento es tu mejor vendedor. Pídele referidos y dale un motivo para recomendarte." },
    ],
  },
  {
    id: "personal",
    name: "Finanzas personales",
    icon: "Wallet",
    color: "sky",
    summary: "El mismo método aplicado a tu vida, no solo al negocio.",
    tips: [
      { id: "p1", title: "Págate primero", tags: ["personal", "ahorro"],
        body: "Apenas te llega dinero, separa tu ahorro e inversión antes de cualquier gasto. Lo que queda es para vivir, no al revés." },
      { id: "p2", title: "Divide tu dinero personal en cuentas", tags: ["personal"],
        body: "Gastos fijos, variables, ahorro, gustos: cada uno en su espacio. Así sabes en tiempo real cuánto te queda para cada cosa." },
      { id: "p3", title: "Ajusta el estilo de vida al sobre", tags: ["personal"],
        body: "Vive con lo que hay en la cuenta de gastos. Si se acaba, se acaba. Ese límite hace más por tus finanzas que cualquier buena intención." },
      { id: "p4", title: "Separa lo personal de lo del negocio", tags: ["personal", "negocio"],
        body: "Mezclar cuentas esconde la realidad de ambos. Tu salario del negocio entra a tu vida como un ingreso claro, no como un préstamo difuso." },
    ],
  },
  {
    id: "ahorro",
    name: "Ahorro y emergencias",
    icon: "PiggyBank",
    color: "violet",
    summary: "Construir un colchón que te dé tranquilidad y opciones.",
    tips: [
      { id: "a1", title: "Automatiza el ahorro", tags: ["ahorro", "personal"],
        body: "Que un porcentaje salga solo a la cuenta de ahorro en cada ingreso. Ahorrar 'lo que sobre' casi nunca funciona." },
      { id: "a2", title: "Meta: 3 a 6 meses de gastos", tags: ["ahorro"],
        body: "Un fondo de emergencia de varios meses te evita caer en deuda ante un imprevisto. Constrúyelo antes de invertir agresivo." },
      { id: "a3", title: "Guárdalo donde no lo veas", tags: ["ahorro"],
        body: "Pon el ahorro en una cuenta separada y de difícil acceso. La fricción para sacarlo es una ventaja, no un estorbo." },
    ],
  },
  {
    id: "impuestos",
    name: "Impuestos",
    icon: "Landmark",
    color: "orange",
    summary: "Que la temporada de impuestos deje de asustarte.",
    tips: [
      { id: "t1", title: "Aparta impuestos en cada ingreso", tags: ["negocio", "impuestos"],
        body: "Manda un porcentaje a una cuenta de impuestos cada vez que entra dinero. Cuando toque pagar, ya está separado y no duele." },
      { id: "t2", title: "Esa cuenta es intocable", tags: ["impuestos"],
        body: "El dinero de impuestos no es tuyo, es del fisco que aún no cobra. Tratarlo como propio es el error que hunde a muchos negocios." },
    ],
  },
  {
    id: "inversion",
    name: "Inversión",
    icon: "LineChart",
    color: "cyan",
    summary: "Poner a trabajar el excedente, sin arriesgar lo esencial.",
    tips: [
      { id: "v1", title: "Invierte el excedente, no la base", tags: ["inversion"],
        body: "Primero ganancia, impuestos y emergencia; recién entonces inviertes. Invertir dinero que necesitas pronto es apostar, no invertir." },
      { id: "v2", title: "Constancia sobre monto", tags: ["inversion"],
        body: "Invertir poco de forma regular vence a esperar 'tener bastante'. El hábito y el tiempo hacen el trabajo pesado." },
      { id: "v3", title: "No pongas todo en un solo lugar", tags: ["inversion"],
        body: "Diversifica para no depender de una sola apuesta. Reduce el riesgo de que un mal año te borre el avance." },
    ],
  },
  {
    id: "habitos",
    name: "Hábitos y mentalidad",
    icon: "Brain",
    color: "rose",
    summary: "La disciplina y la psicología detrás del dinero.",
    tips: [
      { id: "h1", title: "Revisa tus números en fechas fijas", tags: ["negocio", "personal"],
        body: "Agenda un momento cada quincena para repartir y mirar tus cuentas. Lo que se mide con ritmo, se controla." },
      { id: "h2", title: "Celebra la ganancia", tags: ["negocio"],
        body: "Cada cierto tiempo date una parte de la ganancia acumulada como recompensa. Ver el fruto refuerza el hábito de apartar." },
      { id: "h3", title: "Menos disponible, más disciplina", tags: ["negocio", "personal"],
        body: "No dependas de tu fuerza de voluntad. Diseña el sistema (cuentas separadas) para que lo correcto pase casi solo." },
    ],
  },
];
